version: '3.7'
services:
  dashboard:
     #image: housepricepythonuk
     build: 
       context: .
       dockerfile: Dockerfile
     container_name: python_dashboard
     #restart: on-failure:1
     ports:
       - "8050:8050"
     