version: '3.7'
services:
  dashboard:
     image: housepricepythonuk:prod
     build: 
       context: .
       dockerfile: Dockerfile
     container_name: python_dashboard
     #restart: on-failure:1
     ports:
       - "80:80"
     