version: '3.7'
services:
  dashboard:
     build: 
       context: ./
     container_name: python_dashboard
     restart: always
     ports:
       - "8050:8050"
     volumes:
       - /app
       - .:/app
     networks:
       - network 
    
networks:
   network:
     driver: bridge