version: '3.7'
services:
  dashboard:
     image: housepricepythonuk:dev
     build: 
       context: .
       dockerfile: Dockerfile.dev #differs from main
     container_name: python_dashboard_dev #differs from main
     restart: on-failure:1 #differs from main
     ports:
       - "8050:8050"
     volumes: #differs from main
      # changes to files in app folder work correctly
       - "./app:/home/python/app/"
     #networks: #differs from main do we need this line and below?
     #  - network #differs from main#differs from main
    
#networks:
   #network:
     #driver: bridge